#应用配置
server:
  port: 8888
spring:
  application:
    name: apollo-demo

  #Apollo 配置
app:
  id: apollo-test                            #应用ID
apollo:
  cluster: default                           #指定使用哪个集群的配置
  meta: http://127.0.0.1:8080            #DEV环境配置中心地址
  autoUpdateInjectedSpringProperties: true   #是否开启 Spring 参数自动更新
  bootstrap:
    enabled: true                            #是否开启 Apollo
    namespaces: application                  #设置 Namespace
    eagerLoad:
      enabled: false                         #将 Apollo 加载提到初始化日志系统之前
