spring:
  application:
    name: linshen-dubbo-provider1
server:
  port: 9090
dubbo:
  registry:
    protocol: zookeeper
    address: 192.168.0.105:2181
    id: lin-registry-1
  protocol:
    port: 12345
    name: dubbo
    id: dubbo
    status: server
  application:
    name: linshen-dubbo-provider-name1
    id: linshen-dubbo-provider-id1
    qos-enable: true
    qos-port: 22222
  scan:
    basePackages: com.yi.provider.service
  provider:
    mock: true
hello:
  service:
    version: 1.0.0
